### ISSUE TITLE
Using tenants with permission 

### ISSUE THREAD

**Issue by jaydave** [AnalyticsMediaGroup/strongbolt_example#2]
I am able to assign users to individual or group of categories. Lets say I want to restrict user access to article as well. How would I do that ?

- User 1 (Admin) should have access to all categories and article
- User 2 (non-admin) should have access to one category(or group of category) and all article inside that
- User 3 (non-admin) should have access to one category(or group of category) and only 1 article or group of article inside that. I should be able to restrict user from accessing others remaining article from that category

**Comment by tobithiel** [comment]
It sounded like you have `User 1` & `User 2` working and these should be fairly straightforward anyway.

Regarding the `User 3` scenario:
You could make `Article` a tenant as well and then grant these users only tenant access to these articles. You'd have to manually make sure they are in the categories that you'd like though.
You can't grant them tenant access to a category, since that will give them access to all articles in that category.
That happens because Strongbolt only checks that one of the tenant relationships is satisfied. So you can think of it like an `OR` operation logically. As soon as one is satisfied access is granted.

Let me know if that helped or is unclear.

**Comment by jaydave** [comment]
Yes, first scenarios are working fine.

for User 3 scenario, I created entry in `strongbolt_users_tenants` with user_id (3), article_id(8), and Strongbolt::UsersArticle. Also added `Article` in tenants in initializer files. 

I see there errors:
- for user-2 `find permission not granted to User:2 for resource Category:1` and do not see any article. Although, it does not throw error when visit articles
- for user-3, visiting article throws `find permission not granted to User:3 for resource Article:8`

Looks like I am doing something wrong. Please guide me in this

**Comment by tobithiel** [comment]
I tried this out myself and there seems to be an issue with our tenant checking when multiple tenants are connected to the same model.
We'll have to investigate this a bit more thoroughly before changing that. I'll get back to you on this.

**Comment by tobithiel** [comment]
@jaydave We've just released a new version of Strongbolt, which should fix the issue with multiple tenants being connected to the same model.
Please try again.
Be aware that the `accessible_categories` and `accessible_articles` helper methods only take their tenant into account. You'll probably have to construct the overall accessible articles/categories out of both of these methods.
